//! The complete fitting pipeline (`glycoflow/fitting/pipeline.py::fit_site`).
//!
//! 1. propose: observation-guided GlycoFlow generation (method B) -> distinct refined basins;
//! 2. polish: longer, smaller-step refinement of the best few basins;
//! 3. support: which subtrees the observation supports;
//! 4. complete: unsupported subtrees regenerated by GlycoFlow conditioned on the supported part
//!    (prior-driven alternatives, flagged as such);
//! 5. alternatives: distinct basins within `alt_margin` objective units of the best
//!    (density-ambiguous alternatives; objective differences, not calibrated probabilities).

use web_time::Instant;

use glycoflow_core::sampler::{Method, Sampler};
use rayon::prelude::*;
use reglyco_density::DensityMap;
use reglyco_density::site_likelihood::{
    SiteEnvironmentAtom, SiteLikelihood, SiteLikelihoodOptions,
};

use crate::cartesian::{
    CartesianFit, RestraintOptions, cartesian_refine, cartesian_refine_all, cartesian_refine_traced,
};
use crate::counter::CounterSnapshot;
use crate::error::{Result, invalid};
use crate::model::GlycoflowModel;
use crate::observation::{DensityObservation, Observation};
use crate::prior::{MarginalPrior, PriorDeviation, RARE_PERCENTILE, RareTorsion};
use crate::problem::{Pose, ProblemOptions, SiteProblem, Terms, V3, build_glycan, max_span};
use crate::search::{method_b, refine, sample_free};
use crate::site::Site;
use crate::support::{
    Completion, SubtreeSupport, complete_from_prior, subtree_support, unsupported_torsions,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct FitConfig {
    pub seed: u64,
    // defaults: support threshold 5 + 0.5 per torsion (calibrated on synthetic maps with known
    // absent residues); 384 samples x 8 Heun steps (same core/supported recovery and validity as
    // 768 x 32 on 6 X-ray and cryo-EM sites x 3 seeds, at ~1/8 of the network evaluations)
    pub n_samples: usize,
    pub n_basins: usize,
    pub refine_steps: usize,
    pub refine_lr: f64,
    pub polish_top: usize,
    pub polish_steps: usize,
    pub polish_lr: f64,
    pub support_base: f64,
    pub support_per_torsion: f64,
    pub n_completions: usize,
    pub completion_guidance: f32,
    pub alt_margin: f64,
    pub flow_steps: usize,
    pub guidance_scale: f64,
    pub guidance_start: f64,
    /// contact-energy weight (w_env = w_self) during the search
    pub search_clash_weight: f64,
    /// contact-energy weight of the final objective (None: keep the search weight). Every retained
    /// basin is re-scored with it, the best few are refined under it, and selection, support,
    /// completions and alternatives use it (continuation; one objective for all final comparisons).
    pub final_clash_weight: Option<f64>,
    pub steric_steps: usize,
    pub steric_lr: f64,
    /// Contact-validity escalation: while the selected pose's raw contact energy
    /// (E_env + E_self, squared floor violations) exceeds `contact_tolerance`, multiply the final
    /// contact weight by 10, re-score every basin, refine the best few and re-select (at most
    /// `max_escalations` times). The floors sit >= 0.08 A above the validator's van der Waals
    /// limits, so a tolerance of 0.08^2 guarantees no single pair violates them.
    pub contact_tolerance: f64,
    pub max_escalations: usize,
    /// Restrained Cartesian refinement of every retained basin (0: torsion space only), at
    /// `cartesian_clash_weight` with the same contact escalation; basins are then ranked on
    /// objective + restraint energy (`cartesian.rs`).
    pub cartesian_steps: usize,
    pub cartesian_lr: f64,
    pub cartesian_clash_weight: f64,
    pub restraints: RestraintOptions,
    /// escalate the contact weight in torsion space too (re-ranking every basin under it)
    pub torsion_escalation: bool,
    pub cartesian_escalation: Escalation,
}

/// Contact-weight escalation of the Cartesian stage.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Escalation {
    /// refine and re-rank every basin under the escalated weight
    Rerank,
    /// rank once at the final contact weight; only the selected basin is refined under higher
    /// weights (and re-scored at the final weight), so contacts never dominate the ranking
    Selected,
}

impl Default for FitConfig {
    fn default() -> Self {
        Self {
            seed: 0,
            n_samples: 384,
            n_basins: 24,
            refine_steps: 150,
            refine_lr: 0.03,
            polish_top: 4,
            polish_steps: 300,
            polish_lr: 0.01,
            support_base: 5.0,
            support_per_torsion: 0.5,
            n_completions: 16,
            completion_guidance: 0.3,
            alt_margin: 5.0,
            flow_steps: 8,
            guidance_scale: 2.0,
            guidance_start: 0.3,
            search_clash_weight: 10.0,
            final_clash_weight: Some(100.0),
            steric_steps: 150,
            steric_lr: 0.005,
            contact_tolerance: 0.0064,
            max_escalations: 2,
            cartesian_steps: 300,
            cartesian_lr: 0.005,
            cartesian_clash_weight: 100.0,
            restraints: RestraintOptions::default(),
            torsion_escalation: false,
            cartesian_escalation: Escalation::Selected,
        }
    }
}

/// GlycoFlow marginal prior settings (`MarginalPrior.from_model`).
#[derive(Debug, Clone, serde::Serialize)]
pub struct PriorConfig {
    pub enabled: bool,
    pub n_samples: usize,
    pub steps: usize,
    pub bandwidth_deg: f64,
    pub seed: u64,
}

impl Default for PriorConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            n_samples: 512,
            steps: 16,
            bandwidth_deg: 12.0,
            seed: 1234,
        }
    }
}

/// Sigma calibration (`diagnostics.calibrate_sigma`): the atom width at which the protein shell
/// 4-12 A from the link atom, scored as if it were the glycan against the remaining environment,
/// best explains the map (partial correlation). Independent of any glycan candidate.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SigmaCalibration {
    pub selected: f64,
    pub curve: Vec<(f64, f64)>,
}

pub const SIGMA_GRID: [f64; 7] = [0.6, 0.8, 1.0, 1.2, 1.4, 1.7, 2.0];

fn env_atoms(site: &Site, filter: impl Fn(&[f64; 3]) -> bool) -> Vec<SiteEnvironmentAtom> {
    site.environment
        .iter()
        .filter(|a| filter(&a.position))
        .map(|a| SiteEnvironmentAtom {
            position: a.position,
            atomic_number: a.atomic_number,
        })
        .collect()
}

pub fn calibrate_sigma(site: &Site, map: &DensityMap, resolution: f64) -> Result<SigmaCalibration> {
    let (inner, outer) = (4.0f32, 12.0f32);
    let link = site.anchor[2];
    // float32 distances, as the reference computes them on float32 arrays
    let in_shell = |p: &[f64; 3]| {
        let d = (0..3)
            .map(|k| (p[k] as f32 - link[k] as f32).powi(2))
            .fold(0f32, |a, b| a + b)
            .sqrt();
        d > inner && d < outer
    };
    let shell = env_atoms(site, in_shell);
    let rest = env_atoms(site, |p| !in_shell(p));
    let positions: Vec<[f64; 3]> = shell.iter().map(|a| a.position).collect();
    let z: Vec<f64> = shell.iter().map(|a| a.atomic_number).collect();
    let curve = SIGMA_GRID
        .par_iter()
        .map(|&sigma| {
            let options = SiteLikelihoodOptions {
                sigma_angstrom: sigma,
                spacing_angstrom: 0.5,
                radius_angstrom: outer as f64 + 2.0,
                resolution_angstrom: resolution,
                periodic: map.is_full_unit_cell(),
                independent_volume: Some(1.0),
                solvent_distance: Some(reglyco_density::site_likelihood::SOLVENT_DISTANCE),
            };
            let lik = SiteLikelihood::from_map(map, link, &rest, options)?;
            Ok((
                sigma,
                lik.evaluate(&positions, &z, None).partial_correlation,
            ))
        })
        .collect::<Result<Vec<_>>>()?;
    let selected = curve
        .iter()
        .fold(
            (f64::NAN, f64::MIN),
            |best, &(s, c)| if c > best.1 { (s, c) } else { best },
        )
        .0;
    Ok(SigmaCalibration { selected, curve })
}

/// Build the density fitting problem of a site.
pub fn density_problem(
    site: &Site,
    model: &GlycoflowModel,
    map: &DensityMap,
    sigma: f64,
    resolution: f64,
    options: &ProblemOptions,
) -> Result<SiteProblem> {
    let glycan = build_glycan(
        &model.library,
        &site.sequence.sequence,
        options.n_templates,
        options.template_seed,
    )?;
    let radius = options
        .region_radius
        .unwrap_or_else(|| max_span(&glycan) + 2.5);
    let lik_options = SiteLikelihoodOptions {
        sigma_angstrom: sigma,
        spacing_angstrom: 0.5,
        radius_angstrom: radius,
        resolution_angstrom: resolution,
        periodic: map.is_full_unit_cell(),
        independent_volume: None,
        solvent_distance: Some(reglyco_density::site_likelihood::SOLVENT_DISTANCE),
    };
    let env = env_atoms(site, |_| true);
    let likelihood = SiteLikelihood::from_map(map, site.anchor[2], &env, lik_options)?;
    let grid_box = (
        likelihood.obs_blur.origin,
        likelihood.obs_blur.spacing,
        likelihood.obs_blur.dims,
    );
    let observation: Box<dyn Observation> = Box::new(DensityObservation::new(likelihood));
    SiteProblem::new(
        site,
        glycan,
        &model.meta.vocab,
        observation,
        grid_box,
        radius,
        options,
    )
}

/// Candidate-independent constants of a density problem (box, protein-only fit, noise).
#[derive(Debug, Clone, serde::Serialize)]
pub struct DensityConstants {
    pub radius: f64,
    pub origin: [f64; 3],
    pub dims: [usize; 3],
    pub spacing: f64,
    pub sigma: f64,
    /// environment-only fit (a0, b0, bulk-solvent level c_s0)
    pub theta: [f64; 3],
    pub sse0: f64,
    pub noise_variance: f64,
    /// independent-sample volume (A^3) from the residual autocorrelation
    pub independent_volume: f64,
    /// empirical noise inflation (decoy null, >= 1)
    pub inflation: f64,
}

pub fn density_constants(problem: &SiteProblem) -> Option<DensityConstants> {
    let lik = problem.observation.density()?;
    Some(DensityConstants {
        radius: lik.radius,
        origin: lik.obs_blur.origin,
        dims: lik.obs_blur.dims,
        spacing: lik.obs_blur.spacing,
        sigma: lik.sigma,
        theta: lik.theta,
        sse0: lik.sse0,
        noise_variance: lik.noise_variance,
        independent_volume: lik.independent_volume,
        inflation: lik.inflation,
    })
}

/// Draw GlycoFlow samples of the free glycan and build the marginal prior.
pub fn build_prior(
    problem: &SiteProblem,
    sampler: &Sampler,
    config: &PriorConfig,
) -> Result<MarginalPrior> {
    let taus = sample_free(
        problem,
        sampler,
        config.n_samples,
        config.steps,
        Method::Euler,
        config.seed,
    )?;
    Ok(MarginalPrior::new(
        taus.concat(),
        problem.n_torsions,
        config.bandwidth_deg,
    ))
}

/// One retained basin.
#[derive(Debug, Clone)]
pub struct Basin {
    pub pose: Pose,
    pub x: Vec<V3>,
    pub terms: Terms,
    /// objective before refinement
    pub unrefined: f64,
    /// restraint energy of the Cartesian stage (0 without it); basins are ranked on
    /// terms.total + e_restraint
    pub e_restraint: f64,
}

pub struct FitOutcome {
    pub basins: Vec<Basin>,
    /// basin indices by objective
    pub order: Vec<usize>,
    pub best: usize,
    pub support: Vec<SubtreeSupport>,
    pub free_torsions: Vec<bool>,
    pub completions: Vec<Completion>,
    /// basins within `alt_margin` of the best (the best included), by objective
    pub alternatives: Vec<usize>,
    pub counters: CounterSnapshot,
    pub wall_seconds: f64,
    /// contact weight of the final objective (after any escalation)
    pub final_contact_weight: f64,
    /// how far the selected pose is from what GlycoFlow generates (None without a prior)
    pub prior_deviation: Option<PriorDeviation>,
}

/// Prior diagnostics of a placed pose: torsions measured on the coordinates.
pub fn prior_deviation(problem: &SiteProblem, x: &[V3]) -> Option<PriorDeviation> {
    let prior = problem.prior.as_ref()?;
    let quads = &problem.glycan.topology.quads;
    let tau: Vec<f64> = quads
        .iter()
        .map(|q| crate::problem::dihedral(x[q[0]], x[q[1]], x[q[2]], x[q[3]]))
        .collect();
    let pct = prior.percentiles(&tau);
    let names = &problem.glycan.atom_names;
    let rare_torsions = quads
        .iter()
        .enumerate()
        .filter(|(t, _)| pct[*t] < RARE_PERCENTILE)
        .map(|(t, q)| RareTorsion {
            torsion: format!(
                "{}:{}",
                problem.glycan.res_paths[q[1]],
                q.iter()
                    .map(|&i| names[i].as_str())
                    .collect::<Vec<_>>()
                    .join("-")
            ),
            degrees: tau[t].to_degrees(),
            percentile: pct[t],
        })
        .collect();
    Some(PriorDeviation {
        e_prior: prior.energy(&tau, None),
        rare_torsions,
        n_torsions: tau.len(),
    })
}

/// Fit one site (`pipeline.fit_site`). The problem's prior (if any) must already be set. The
/// problem is left with the final contact weights, so later evaluations use the final objective.
pub fn fit_site(
    problem: &mut SiteProblem,
    sampler: &Sampler,
    config: &FitConfig,
) -> Result<FitOutcome> {
    if config.n_samples == 0 || config.n_basins == 0 || config.flow_steps == 0 {
        return Err(invalid(
            "samples, basins and flow steps must each be at least 1",
        ));
    }
    let started = Instant::now();
    problem.w_env = config.search_clash_weight;
    problem.w_self = config.search_clash_weight;
    let observer = problem.observer.clone();
    let observer = observer.get();
    // search on the (smoother) search weights
    let (mut poses, mut energies, unrefined, sources) = {
        let problem: &SiteProblem = problem;
        let c = &problem.counter;
        let r = method_b(
            problem,
            sampler,
            config.n_samples,
            config.n_basins,
            config.refine_steps,
            config.refine_lr,
            config.flow_steps,
            config.guidance_scale,
            config.guidance_start,
            config.seed,
        )?;
        let mut poses = r.poses;
        let mut energies = r.energies;
        let t0 = Instant::now();
        if let Some(o) = observer {
            o.stage("polish");
        }
        polish_top(
            problem,
            &mut poses,
            &mut energies,
            config.polish_top,
            config.polish_steps,
            config.polish_lr,
        );
        c.add_stage("polish", t0);
        if let Some(o) = observer {
            o.basins("polish", &r.sources, &poses, &energies);
        }
        (poses, energies, r.unrefined, r.sources)
    };
    // final objective: re-score every basin, refine the best few under it; escalate the contact
    // weight while the selected pose still violates the contact floors
    let mut final_contact_weight = problem.w_env;
    if let Some(w0) = config.final_clash_weight {
        let mut w = w0;
        let rounds = if config.torsion_escalation {
            config.max_escalations
        } else {
            0
        };
        for round in 0..=rounds {
            problem.w_env = w;
            problem.w_self = w;
            final_contact_weight = w;
            let problem: &SiteProblem = problem;
            let t0 = Instant::now();
            if let Some(o) = observer {
                o.stage(if round == 0 { "steric polish" } else { "steric escalation" });
            }
            energies = poses
                .par_iter()
                .map(|pose| problem.evaluate(pose, false).terms.total)
                .collect();
            problem.counter.add_objective(poses.len());
            polish_top(
                problem,
                &mut poses,
                &mut energies,
                config.polish_top,
                config.steric_steps,
                config.steric_lr,
            );
            let stage = if round == 0 {
                "steric polish"
            } else {
                "steric escalation"
            };
            problem.counter.add_stage(stage, t0);
            if let Some(o) = observer {
                o.basins(stage, &sources, &poses, &energies);
            }
            let best = (0..energies.len())
                .min_by(|&a, &b| energies[a].total_cmp(&energies[b]))
                .unwrap_or(0);
            let t = problem.evaluate(&poses[best], false).terms;
            if t.e_env + t.e_self <= config.contact_tolerance {
                break;
            }
            w *= 10.0;
        }
    }
    // restrained Cartesian refinement of every basin, with the same contact escalation
    let mut cartesian: Option<Vec<CartesianFit>> = None;
    if config.cartesian_steps > 0 {
        let t0 = Instant::now();
        if let Some(o) = observer {
            o.stage("cartesian");
        }
        let templates: Vec<usize> = poses.iter().map(|p| p.template).collect();
        let mut xs: Vec<Vec<V3>> = {
            let problem: &SiteProblem = problem;
            poses.par_iter().map(|p| problem.place(p)).collect()
        };
        let w0 = config.cartesian_clash_weight;
        let argmin = |fits: &[CartesianFit]| {
            (0..fits.len())
                .min_by(|&a, &b| fits[a].total.total_cmp(&fits[b].total))
                .unwrap_or(0)
        };
        let clear = |f: &CartesianFit| f.terms.e_env + f.terms.e_self <= config.contact_tolerance;
        match config.cartesian_escalation {
            Escalation::Rerank => {
                let mut w = w0;
                for _ in 0..=config.max_escalations {
                    problem.w_env = w;
                    problem.w_self = w;
                    final_contact_weight = w;
                    let fits = cartesian_refine_all(
                        problem,
                        &xs,
                        &templates,
                        config.cartesian_steps,
                        config.cartesian_lr,
                        &config.restraints,
                    );
                    let ok = clear(&fits[argmin(&fits)]);
                    xs = fits.iter().map(|f| f.x.clone()).collect();
                    cartesian = Some(fits);
                    if ok {
                        break;
                    }
                    w *= 10.0;
                }
            }
            Escalation::Selected => {
                problem.w_env = w0;
                problem.w_self = w0;
                final_contact_weight = w0;
                let mut fits = cartesian_refine_all(
                    problem,
                    &xs,
                    &templates,
                    config.cartesian_steps,
                    config.cartesian_lr,
                    &config.restraints,
                );
                for attempt in 0..config.max_escalations {
                    let b = argmin(&fits);
                    if clear(&fits[b]) {
                        break;
                    }
                    let factor = 10f64.powi(attempt as i32 + 1);
                    let w = w0 * factor;
                    problem.w_env = w;
                    problem.w_self = w;
                    final_contact_weight = w;
                    // restraints escalate with the contacts (sd / sqrt(factor)): only the density
                    // is down-weighted, so clearing a contact never distorts the ring geometry
                    let r = &config.restraints;
                    let scaled = RestraintOptions {
                        sd_bond: r.sd_bond / factor.sqrt(),
                        sd_angle: r.sd_angle / factor.sqrt(),
                        sd_volume: r.sd_volume / factor.sqrt(),
                    };
                    let pass = format!("escalation x{factor}");
                    let up = cartesian_refine_traced(
                        problem,
                        &fits[b].x,
                        templates[b],
                        config.cartesian_steps,
                        config.cartesian_lr,
                        &scaled,
                        Some((b, pass.as_str())),
                    );
                    problem.counter.add_objective_grad(config.cartesian_steps);
                    problem.w_env = w0;
                    problem.w_self = w0;
                    // re-scored at the ranking weight
                    fits[b] = cartesian_refine(
                        problem,
                        &up.x,
                        templates[b],
                        0,
                        config.cartesian_lr,
                        &config.restraints,
                    );
                }
                cartesian = Some(fits);
            }
        }
        problem.counter.add_stage("cartesian", t0);
    }
    let problem: &SiteProblem = problem;
    let c = &problem.counter;
    let t0 = Instant::now();
    if let Some(o) = observer {
        o.stage("support+complete");
    }
    let basins: Vec<Basin> = match cartesian {
        Some(fits) => {
            energies = fits.iter().map(|f| f.total).collect();
            poses
                .into_iter()
                .zip(fits)
                .zip(&unrefined)
                .map(|((mut pose, fit), &unrefined)| {
                    pose.psi = fit.psi;
                    Basin {
                        pose,
                        x: fit.x,
                        terms: fit.terms,
                        unrefined,
                        e_restraint: fit.e_restraint,
                    }
                })
                .collect()
        }
        None => {
            let evaluated: Vec<_> = poses
                .par_iter()
                .map(|p| problem.evaluate(p, false))
                .collect();
            poses
                .into_iter()
                .zip(evaluated)
                .zip(&unrefined)
                .map(|((pose, ev), &unrefined)| Basin {
                    pose,
                    x: ev.x,
                    terms: ev.terms,
                    unrefined,
                    e_restraint: 0.0,
                })
                .collect()
        }
    };
    if let Some(o) = observer {
        let poses: Vec<Pose> = basins.iter().map(|b| b.pose.clone()).collect();
        o.basins("final", &sources, &poses, &energies);
    }
    let mut order: Vec<usize> = (0..energies.len()).collect();
    order.sort_by(|&a, &b| energies[a].total_cmp(&energies[b]));
    let best = order[0];
    let support = subtree_support(
        problem,
        &basins[best].x,
        config.support_base,
        config.support_per_torsion,
    );
    let free = unsupported_torsions(problem, &support);
    let completions = if free.iter().any(|f| *f) {
        complete_from_prior(
            problem,
            sampler,
            &basins[best].pose,
            &free,
            config.n_completions,
            config.flow_steps,
            config.completion_guidance,
            config.seed,
        )?
    } else {
        Vec::new()
    };
    c.add_stage("support+complete", t0);
    let alternatives = order
        .iter()
        .copied()
        .filter(|&i| energies[i] - energies[best] <= config.alt_margin)
        .collect();
    let deviation = prior_deviation(problem, &basins[best].x);
    Ok(FitOutcome {
        basins,
        order,
        best,
        support,
        free_torsions: free,
        completions,
        alternatives,
        counters: c.snapshot(),
        wall_seconds: started.elapsed().as_secs_f64(),
        final_contact_weight,
        prior_deviation: deviation,
    })
}

/// Refine the `top` lowest-objective poses (Adam) and keep improvements.
fn polish_top(
    problem: &SiteProblem,
    poses: &mut [Pose],
    energies: &mut [f64],
    top: usize,
    steps: usize,
    lr: f64,
) {
    let mut order: Vec<usize> = (0..energies.len()).collect();
    order.sort_by(|&a, &b| energies[a].total_cmp(&energies[b]));
    let top: Vec<usize> = order.into_iter().take(top).collect();
    let starts: Vec<Pose> = top.iter().map(|&i| poses[i].clone()).collect();
    for (&i, (pose, e)) in top.iter().zip(refine(problem, &starts, steps, lr)) {
        if e < energies[i] {
            poses[i] = pose;
            energies[i] = e;
        }
    }
}
