//! The complete fitting pipeline (`glycoflow/fitting/pipeline.py::fit_site`).
//!
//! 1. propose: observation-guided GlycoFlow generation (method B) -> distinct refined basins;
//! 2. polish: longer, smaller-step refinement of the best few basins;
//! 3. support: which subtrees the observation supports;
//! 4. complete: unsupported subtrees regenerated by GlycoFlow conditioned on the supported part
//!    (prior-driven alternatives, flagged as such);
//! 5. alternatives: distinct basins within `alt_margin` objective units of the best
//!    (density-ambiguous alternatives; objective differences, not calibrated probabilities).

use std::time::Instant;

use glycoflow_core::sampler::{Method, Sampler};
use rayon::prelude::*;
use reglyco_density::DensityMap;
use reglyco_density::site_likelihood::{
    SiteEnvironmentAtom, SiteLikelihood, SiteLikelihoodOptions,
};

use crate::counter::CounterSnapshot;
use crate::error::Result;
use crate::model::GlycoflowModel;
use crate::observation::{DensityObservation, Observation};
use crate::prior::MarginalPrior;
use crate::problem::{Pose, ProblemOptions, SiteProblem, Terms, V3, build_glycan, max_span};
use crate::search::{method_b, refine, sample_free};
use crate::site::Site;
use crate::support::{
    Completion, SubtreeSupport, complete_from_prior, subtree_support, unsupported_torsions,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct FitConfig {
    pub seed: u64,
    // defaults: the calibrated reference settings (support threshold 3 + 0.5 per torsion,
    // calibrated on synthetic maps with known absent residues)
    pub n_samples: usize,
    pub n_basins: usize,
    pub refine_steps: usize,
    pub refine_lr: f64,
    pub polish_top: usize,
    pub polish_steps: usize,
    pub polish_lr: f64,
    pub support_base: f64,
    pub support_per_torsion: f64,
    pub n_completions: usize,
    pub completion_guidance: f32,
    pub alt_margin: f64,
    pub flow_steps: usize,
    pub guidance_scale: f64,
    pub guidance_start: f64,
    /// contact-energy weight (w_env = w_self) during the search
    pub search_clash_weight: f64,
    /// contact-energy weight of the final objective (None: keep the search weight). Every retained
    /// basin is re-scored with it, the best few are refined under it, and selection, support,
    /// completions and alternatives use it (continuation; one objective for all final comparisons).
    pub final_clash_weight: Option<f64>,
    pub steric_steps: usize,
    pub steric_lr: f64,
}

impl Default for FitConfig {
    fn default() -> Self {
        Self {
            seed: 0,
            n_samples: 768,
            n_basins: 24,
            refine_steps: 150,
            refine_lr: 0.03,
            polish_top: 4,
            polish_steps: 300,
            polish_lr: 0.01,
            support_base: 3.0,
            support_per_torsion: 0.5,
            n_completions: 16,
            completion_guidance: 0.3,
            alt_margin: 5.0,
            flow_steps: 32,
            guidance_scale: 1.0,
            guidance_start: 0.3,
            search_clash_weight: 10.0,
            final_clash_weight: Some(100.0),
            steric_steps: 150,
            steric_lr: 0.005,
        }
    }
}

/// GlycoFlow marginal prior settings (`MarginalPrior.from_model`).
#[derive(Debug, Clone, serde::Serialize)]
pub struct PriorConfig {
    pub enabled: bool,
    pub n_samples: usize,
    pub steps: usize,
    pub bandwidth_deg: f64,
    pub seed: u64,
}

impl Default for PriorConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            n_samples: 512,
            steps: 16,
            bandwidth_deg: 12.0,
            seed: 1234,
        }
    }
}

/// Sigma calibration (`diagnostics.calibrate_sigma`): the atom width at which the protein shell
/// 4-12 A from the link atom, scored as if it were the glycan against the remaining environment,
/// best explains the map (partial correlation). Independent of any glycan candidate.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SigmaCalibration {
    pub selected: f64,
    pub curve: Vec<(f64, f64)>,
}

pub const SIGMA_GRID: [f64; 7] = [0.6, 0.8, 1.0, 1.2, 1.4, 1.7, 2.0];

fn env_atoms(site: &Site, filter: impl Fn(&[f64; 3]) -> bool) -> Vec<SiteEnvironmentAtom> {
    site.environment
        .iter()
        .filter(|a| filter(&a.position))
        .map(|a| SiteEnvironmentAtom {
            position: a.position,
            atomic_number: a.atomic_number,
        })
        .collect()
}

pub fn calibrate_sigma(site: &Site, map: &DensityMap, resolution: f64) -> Result<SigmaCalibration> {
    let (inner, outer) = (4.0f32, 12.0f32);
    let link = site.anchor[2];
    // float32 distances, as the reference computes them on float32 arrays
    let in_shell = |p: &[f64; 3]| {
        let d = (0..3)
            .map(|k| (p[k] as f32 - link[k] as f32).powi(2))
            .fold(0f32, |a, b| a + b)
            .sqrt();
        d > inner && d < outer
    };
    let shell = env_atoms(site, in_shell);
    let rest = env_atoms(site, |p| !in_shell(p));
    let positions: Vec<[f64; 3]> = shell.iter().map(|a| a.position).collect();
    let z: Vec<f64> = shell.iter().map(|a| a.atomic_number).collect();
    let curve = SIGMA_GRID
        .par_iter()
        .map(|&sigma| {
            let options = SiteLikelihoodOptions {
                sigma_angstrom: sigma,
                spacing_angstrom: 0.5,
                radius_angstrom: outer as f64 + 2.0,
                resolution_angstrom: resolution,
                periodic: map.is_full_unit_cell(),
                independent_volume: Some(1.0),
            };
            let lik = SiteLikelihood::from_map(map, link, &rest, options)?;
            Ok((
                sigma,
                lik.evaluate(&positions, &z, None).partial_correlation,
            ))
        })
        .collect::<Result<Vec<_>>>()?;
    let selected = curve
        .iter()
        .fold(
            (f64::NAN, f64::MIN),
            |best, &(s, c)| if c > best.1 { (s, c) } else { best },
        )
        .0;
    Ok(SigmaCalibration { selected, curve })
}

/// Build the density fitting problem of a site.
pub fn density_problem(
    site: &Site,
    model: &GlycoflowModel,
    map: &DensityMap,
    sigma: f64,
    resolution: f64,
    options: &ProblemOptions,
) -> Result<SiteProblem> {
    let glycan = build_glycan(
        &model.library,
        &site.sequence.sequence,
        options.n_templates,
        options.template_seed,
    )?;
    let radius = options
        .region_radius
        .unwrap_or_else(|| max_span(&glycan) + 2.5);
    let lik_options = SiteLikelihoodOptions {
        sigma_angstrom: sigma,
        spacing_angstrom: 0.5,
        radius_angstrom: radius,
        resolution_angstrom: resolution,
        periodic: map.is_full_unit_cell(),
        independent_volume: None,
    };
    let env = env_atoms(site, |_| true);
    let likelihood = SiteLikelihood::from_map(map, site.anchor[2], &env, lik_options)?;
    let grid_box = (
        likelihood.obs_blur.origin,
        likelihood.obs_blur.spacing,
        likelihood.obs_blur.dims,
    );
    let observation: Box<dyn Observation> = Box::new(DensityObservation::new(likelihood));
    SiteProblem::new(
        site,
        glycan,
        &model.meta.vocab,
        observation,
        grid_box,
        radius,
        options,
    )
}

/// Candidate-independent constants of a density problem (box, protein-only fit, noise).
#[derive(Debug, Clone, serde::Serialize)]
pub struct DensityConstants {
    pub radius: f64,
    pub origin: [f64; 3],
    pub dims: [usize; 3],
    pub spacing: f64,
    pub sigma: f64,
    /// protein-only fit (a0, b0)
    pub theta: [f64; 2],
    pub sse0: f64,
    pub noise_variance: f64,
    /// independent-sample volume (A^3) from the residual autocorrelation
    pub independent_volume: f64,
}

pub fn density_constants(problem: &SiteProblem) -> Option<DensityConstants> {
    let lik = problem.observation.density()?;
    Some(DensityConstants {
        radius: lik.radius,
        origin: lik.obs_blur.origin,
        dims: lik.obs_blur.dims,
        spacing: lik.obs_blur.spacing,
        sigma: lik.sigma,
        theta: lik.theta,
        sse0: lik.sse0,
        noise_variance: lik.noise_variance,
        independent_volume: lik.independent_volume,
    })
}

/// Draw GlycoFlow samples of the free glycan and build the marginal prior.
pub fn build_prior(
    problem: &SiteProblem,
    sampler: &Sampler,
    config: &PriorConfig,
) -> Result<MarginalPrior> {
    let taus = sample_free(
        problem,
        sampler,
        config.n_samples,
        config.steps,
        Method::Euler,
        config.seed,
    )?;
    Ok(MarginalPrior::new(
        taus.concat(),
        problem.n_torsions,
        config.bandwidth_deg,
    ))
}

/// One retained basin.
#[derive(Debug, Clone)]
pub struct Basin {
    pub pose: Pose,
    pub x: Vec<V3>,
    pub terms: Terms,
    /// objective before refinement
    pub unrefined: f64,
}

pub struct FitOutcome {
    pub basins: Vec<Basin>,
    /// basin indices by objective
    pub order: Vec<usize>,
    pub best: usize,
    pub support: Vec<SubtreeSupport>,
    pub free_torsions: Vec<bool>,
    pub completions: Vec<Completion>,
    /// basins within `alt_margin` of the best (the best included), by objective
    pub alternatives: Vec<usize>,
    pub counters: CounterSnapshot,
    pub wall_seconds: f64,
}

/// Fit one site (`pipeline.fit_site`). The problem's prior (if any) must already be set. The
/// problem is left with the final contact weights, so later evaluations use the final objective.
pub fn fit_site(
    problem: &mut SiteProblem,
    sampler: &Sampler,
    config: &FitConfig,
) -> Result<FitOutcome> {
    let started = Instant::now();
    problem.w_env = config.search_clash_weight;
    problem.w_self = config.search_clash_weight;
    // search on the (smoother) search weights
    let (mut poses, mut energies, unrefined) = {
        let problem: &SiteProblem = problem;
        let c = &problem.counter;
        let r = method_b(
            problem,
            sampler,
            config.n_samples,
            config.n_basins,
            config.refine_steps,
            config.refine_lr,
            config.flow_steps,
            config.guidance_scale,
            config.guidance_start,
            config.seed,
        )?;
        let mut poses = r.poses;
        let mut energies = r.energies;
        let t0 = Instant::now();
        polish_top(
            problem,
            &mut poses,
            &mut energies,
            config.polish_top,
            config.polish_steps,
            config.polish_lr,
        );
        c.add_stage("polish", t0);
        (poses, energies, r.unrefined)
    };
    // final objective: re-score every basin, refine the best few under it
    if let Some(w) = config.final_clash_weight {
        problem.w_env = w;
        problem.w_self = w;
        let problem: &SiteProblem = problem;
        let t0 = Instant::now();
        energies = poses
            .par_iter()
            .map(|pose| problem.evaluate(pose, false).terms.total)
            .collect();
        problem.counter.add_objective(poses.len());
        polish_top(
            problem,
            &mut poses,
            &mut energies,
            config.polish_top,
            config.steric_steps,
            config.steric_lr,
        );
        problem.counter.add_stage("steric polish", t0);
    }
    let problem: &SiteProblem = problem;
    let c = &problem.counter;
    let t0 = Instant::now();
    let evaluated: Vec<_> = poses
        .par_iter()
        .map(|p| problem.evaluate(p, false))
        .collect();
    let basins: Vec<Basin> = poses
        .into_iter()
        .zip(evaluated)
        .zip(&unrefined)
        .map(|((pose, ev), &unrefined)| Basin {
            pose,
            x: ev.x,
            terms: ev.terms,
            unrefined,
        })
        .collect();
    let mut order: Vec<usize> = (0..energies.len()).collect();
    order.sort_by(|&a, &b| energies[a].total_cmp(&energies[b]));
    let best = order[0];
    let support = subtree_support(
        problem,
        &basins[best].x,
        config.support_base,
        config.support_per_torsion,
    );
    let free = unsupported_torsions(problem, &support);
    let completions = if free.iter().any(|f| *f) {
        complete_from_prior(
            problem,
            sampler,
            &basins[best].pose,
            &free,
            config.n_completions,
            config.flow_steps,
            config.completion_guidance,
            config.seed,
        )?
    } else {
        Vec::new()
    };
    c.add_stage("support+complete", t0);
    let alternatives = order
        .iter()
        .copied()
        .filter(|&i| energies[i] - energies[best] <= config.alt_margin)
        .collect();
    Ok(FitOutcome {
        basins,
        order,
        best,
        support,
        free_torsions: free,
        completions,
        alternatives,
        counters: c.snapshot(),
        wall_seconds: started.elapsed().as_secs_f64(),
    })
}

/// Refine the `top` lowest-objective poses (Adam) and keep improvements.
fn polish_top(
    problem: &SiteProblem,
    poses: &mut [Pose],
    energies: &mut [f64],
    top: usize,
    steps: usize,
    lr: f64,
) {
    let mut order: Vec<usize> = (0..energies.len()).collect();
    order.sort_by(|&a, &b| energies[a].total_cmp(&energies[b]));
    let top: Vec<usize> = order.into_iter().take(top).collect();
    let starts: Vec<Pose> = top.iter().map(|&i| poses[i].clone()).collect();
    for (&i, (pose, e)) in top.iter().zip(refine(problem, &starts, steps, lr)) {
        if e < energies[i] {
            poses[i] = pose;
            energies[i] = e;
        }
    }
}
