//! Which parts of a fitted glycan the observation supports, and prior completion of the rest
//! (`glycoflow/fitting/support.py`).
//!
//! Support: for every residue r, the log-likelihood the subtree rooted at r explains given the
//! rest of the fitted glycan (subtree atoms removed from the model). Fitting noise with k free
//! torsions also "explains" likelihood, so a subtree counts as supported only when its gain
//! exceeds `base + per_torsion * k` (default 5 + 0.5 k, calibrated on synthetic maps); a child is
//! never supported when its parent is not.
//!
//! Completion: unsupported subtrees are regenerated by GlycoFlow conditioned on the supported
//! part. Supported torsions follow their straight flow path to the fitted value exactly
//! (replacement inpainting, through the sampler's guidance hook), the network generates the
//! others, with protein/self clash guidance only (no observation). These are prior-driven
//! alternatives, not fits.

use glycoflow_core::geometry::{P3, wrap};
use glycoflow_core::sampler::{Guidance, GuidanceContext, Method, SampleOptions, Sampler};
use rayon::prelude::*;

use crate::error::Result;
use crate::problem::{Pose, SiteProblem, Terms, V3};
use crate::search::initial_torsions;

/// Residue paths (without the aglycone) sorted by depth then path, each with its subtree.
pub fn residue_tree(problem: &SiteProblem) -> Vec<(String, Vec<String>)> {
    let mut paths: Vec<String> = problem
        .glycan
        .res_paths
        .iter()
        .filter(|p| *p != "agl")
        .cloned()
        .collect();
    paths.sort();
    paths.dedup();
    paths.sort_by(|a, b| (a.matches('/').count(), a).cmp(&(b.matches('/').count(), b)));
    paths
        .iter()
        .map(|p| {
            let prefix = format!("{p}/");
            (
                p.clone(),
                paths
                    .iter()
                    .filter(|q| *q == p || q.starts_with(&prefix))
                    .cloned()
                    .collect(),
            )
        })
        .collect()
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct SubtreeSupport {
    pub residue: String,
    /// log-likelihood explained by the subtree given the rest of the fit
    pub gain_loglik: f64,
    /// torsions moving only atoms of the subtree
    pub n_torsions: usize,
    pub atoms: usize,
    /// noise allowance base + per_torsion * n_torsions
    pub threshold: f64,
    pub supported: bool,
}

/// Per-subtree support of one placed pose, classified with the given allowance.
pub fn subtree_support(
    problem: &SiteProblem,
    x: &[V3],
    base: f64,
    per_torsion: f64,
) -> Vec<SubtreeSupport> {
    let obs = &problem.observation;
    let full = obs.evaluate(x, None, None).log_likelihood;
    let paths = &problem.glycan.res_paths;
    let distal = &problem.glycan.topology.distal;
    let mut out: Vec<SubtreeSupport> = residue_tree(problem)
        .into_par_iter()
        .filter(|(root, _)| root != "r")
        .map(|(root, members)| {
            let sel: Vec<bool> = paths.iter().map(|p| members.contains(p)).collect();
            let active: Vec<bool> = sel
                .iter()
                .zip(&problem.keep)
                .map(|(s, k)| *k && !s)
                .collect();
            let without = obs.evaluate(x, Some(&active), None).log_likelihood;
            let n_torsions = distal
                .iter()
                .filter(|d| !d.is_empty() && d.iter().all(|&i| sel[i]))
                .count();
            let gain = full - without;
            let threshold = base + per_torsion * n_torsions as f64;
            SubtreeSupport {
                residue: root,
                gain_loglik: gain,
                n_torsions,
                atoms: sel.iter().filter(|s| **s).count(),
                threshold,
                supported: gain > threshold,
            }
        })
        .collect();
    // a residue is supported only when every ancestor subtree is
    for k in 0..out.len() {
        let parent = out[k]
            .residue
            .rsplit_once('/')
            .map(|(p, _)| p.to_string())
            .unwrap_or_default();
        if let Some(p) = out[..k].iter().position(|s| s.residue == parent)
            && !out[p].supported
        {
            out[k].supported = false;
        }
    }
    out
}

/// Torsions that move only atoms of unsupported subtrees.
pub fn unsupported_torsions(problem: &SiteProblem, support: &[SubtreeSupport]) -> Vec<bool> {
    let bad: Vec<bool> = problem
        .glycan
        .res_paths
        .iter()
        .map(|p| {
            p != "agl"
                && p != "r"
                && support
                    .iter()
                    .find(|s| &s.residue == p)
                    .is_some_and(|s| !s.supported)
        })
        .collect();
    problem
        .glycan
        .topology
        .distal
        .iter()
        .map(|d| !d.is_empty() && d.iter().all(|&i| bad[i]))
        .collect()
}

/// Inpainting hook: pinned torsions get their straight-path velocity, free torsions get clash
/// guidance at the predicted endpoint for `t >= start`.
struct CompletionGuidance<'p> {
    problem: &'p SiteProblem,
    pose: Pose,
    free: Vec<bool>,
    /// straight-path velocity of the pinned torsions [B*T]
    delta_pin: Vec<f32>,
    scale: f32,
    start: f64,
}

impl Guidance for CompletionGuidance<'_> {
    fn correction(&mut self, ctx: &GuidanceContext) -> glycoflow_core::Result<Option<Vec<f32>>> {
        let nt = ctx.topology.n_torsions();
        let mut v = ctx.v.to_vec();
        for s in 0..ctx.batch {
            for t in 0..nt {
                if !self.free[t] {
                    v[s * nt + t] = self.delta_pin[s * nt + t];
                }
            }
        }
        let time = ctx.step as f64 * (1.0 / ctx.steps as f64);
        if self.scale > 0.0 && time >= self.start {
            let omt = 1.0 - ctx.t;
            let problem = self.problem;
            let grads: Vec<Vec<f64>> = (0..ctx.batch)
                .into_par_iter()
                .map(|s| {
                    let ahead: Vec<f64> = (0..nt)
                        .map(|t| wrap(ctx.tau[s * nt + t] + omt * v[s * nt + t]) as f64)
                        .collect();
                    clash_gradient(
                        problem,
                        &Pose {
                            tau: ahead,
                            ..self.pose.clone()
                        },
                    )
                })
                .collect();
            for (s, g) in grads.iter().enumerate() {
                for t in 0..nt {
                    if self.free[t] {
                        v[s * nt + t] -= self.scale * (g[t] as f32).clamp(-10.0, 10.0);
                    }
                }
            }
        }
        Ok(Some(v.iter().zip(ctx.v).map(|(a, b)| a - b).collect()))
    }
}

/// d(w_env E_env + w_self E_self)/dtau of a pose (no observation, prior or attachment term).
fn clash_gradient(problem: &SiteProblem, pose: &Pose) -> Vec<f64> {
    let x = problem.place(pose);
    let mut gx = vec![[0.0; 3]; problem.n_atoms];
    problem.clash_terms(&x, Some(&mut gx));
    let topo = &problem.glycan.topology;
    glycoflow_core::geometry::torsion_gradient(&x, &topo.quads, &topo.distal, &gx)
}

/// A prior-driven completion of the unsupported subtrees.
#[derive(Debug, Clone)]
pub struct Completion {
    pub pose: Pose,
    pub x: Vec<V3>,
    pub terms: Terms,
}

/// Regenerate the `free` torsions with GlycoFlow, the others pinned to `fit` (Euler, clash
/// guidance `scale` from t = 0.5; `support.complete_from_prior`).
#[allow(clippy::too_many_arguments)]
pub fn complete_from_prior(
    problem: &SiteProblem,
    sampler: &Sampler,
    fit: &Pose,
    free: &[bool],
    n: usize,
    steps: usize,
    scale: f32,
    seed: u64,
) -> Result<Vec<Completion>> {
    let nt = problem.n_torsions;
    let tau0 = initial_torsions(seed ^ 0xC0_4E_1E_7E, n, nt);
    let target: Vec<f32> = fit.tau.iter().map(|&v| v as f32).collect();
    let mut delta_pin = vec![0f32; n * nt];
    for s in 0..n {
        for t in 0..nt {
            delta_pin[s * nt + t] = wrap(target[t] - tau0[s * nt + t]);
        }
    }
    let mut hook = CompletionGuidance {
        problem,
        pose: fit.clone(),
        free: free.to_vec(),
        delta_pin,
        scale,
        start: 0.5,
    };
    let templates: Vec<P3> = (0..n)
        .flat_map(|_| problem.glycan.templates[fit.template].iter().copied())
        .collect();
    let opts = SampleOptions {
        steps,
        method: Method::Euler,
    };
    let (_, tau) = sampler.sample(&templates, &tau0, opts, Some(&mut hook))?;
    problem.counter.add_nfe(n * opts.nfe());
    Ok((0..n)
        .into_par_iter()
        .map(|s| {
            let tau: Vec<f64> = (0..nt)
                .map(|t| {
                    if free[t] {
                        tau[s * nt + t] as f64
                    } else {
                        fit.tau[t]
                    }
                })
                .collect();
            let pose = Pose { tau, ..fit.clone() };
            let ev = problem.evaluate(&pose, false);
            Completion {
                pose,
                x: ev.x,
                terms: ev.terms,
            }
        })
        .collect())
}
